authors = ["bencamm001 <ben.camm00@gmail.com>"]
name = "Ridgeline"
uuid = "f7583424-a3f8-11eb-20cf-ab5c893203ce"
version = "0.1.0"
repository = "https://github.com/bencamm001/ridgeline.jl"
description = "Ridgeline Plotting in Julia"
keywords = "ridgeline, joy, plot, julia"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
